version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "file-processing-${Environment}"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-${AWS::AccountId}"
s3_prefix = "file-processing"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=${Environment}"
image_repositories = []
