version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shopping-cart-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-${AWS::AccountId}"
s3_prefix = "shopping-cart-serverless"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=dev AdminEmail=admin@example.com"
